### ISSUE TITLE
Not working WebDavSession

### ISSUE THREAD

**Issue by yookjy** [DecaTec/Portable-WebDAV-Library#12]
Hello,
WebDavSession works well until 0.4, but it does not work after updating to 0.5.1.
(But WebDavClient works good.)
Please fix it. 

// The base URL of the WebDAV server.
var webDavServerUrl = "http://192.168.0.250/dav";

// Specify the user credentials and use it to create a WebDavSession instance.
var credentials = new PasswordCredential(webDavServerUrl, "MyUsername", "MyPassword");
var webDavSession = new WebDavSession(@"http://192.168.0.250/dav", credentials);
var items = await webDavSession.ListAsync(@"/");

foreach (var item in items)
{
    // Handle the response (list of WebDavSessionListItems), e.g item.Uri is the URL of an item (folder or file).
}

**Comment by DecaTec** [comment]
It works well with Nextcloud/ownCloud. With WebDavSesion.ListAsync, an empty PropFind is sent to the server.
What WebDAV server you're using? Maybe your server can't handle an empty PropFind. What kind of response di you get from the server?

Do you have a piece of code using the WebDavClient which works for you?

**Comment by yookjy** [comment]
I'm using NAS that manufacturer is ipTime.
It worked well in version 0.4, so it seems to support the empty PropFind.
And WebDavClient code is below. (It is just your exsample, replaced server address, id, pwd)
It works.

// The base URL of the WebDAV server.
var webDavServerUrl = "http://192.168.0.250/dav";

// Specify the user credentials and pass it to a HttpBaseProtocolFilter.
var credentials = new PasswordCredential(webDavServerUrl, "MyUserName", "MyPassword");
var httpBaseProtocolFilter = new HttpBaseProtocolFilter();
httpBaseProtocolFilter.ServerCredential = credentials;

// Use the HttpBaseProtocolFilter (with credentials) to create a new WebDavClient.
var webDavClient = new WebDavClient(httpBaseProtocolFilter);

// Create a PropFind object with represents a so called allprop request.
var pf = PropFind.CreatePropFindAllProp();
var response = await webDavClient.PropFindAsync("192.168.0.250/dav/", WebDavDepthHeaderValue.Infinity, pf);

// You could also use an XML string directly for use with the WebDavClient.
//var xmlString = "&lt;?xml version=\&quot;1.0\&quot; encoding=\&quot;utf-8\&quot;?&gt;&lt;D:propfind xmlns:D=\&quot;DAV:\&quot;&gt;&lt;D:allprop /&gt;&lt;/D:propfind&gt;";
//var response = await webDavClient.PropFindAsync(@"http://www.myserver.com/webdav/MyFolder/", WebDavDepthHeaderValue.Infinity, xmlString);

// Use the WebDavResponseContentParser to parse the response message and get a MultiStatus instance (this is also an async method).
var multistatus = await WebDavResponseContentParser.ParseMultistatusResponseContentAsync(response.Content);

// Now you can use the MultiStatus object to get access to the items properties.
foreach (var responseItem in multistatus.Response)
{
    // Handle propfind multistatus response, e.g responseItem.Href is the URL of an item (folder or file).
}

// Dispose the WebDavClient when it is not longer needed.
webDavClient.Dispose();

**Comment by DecaTec** [comment]
OK, the empty PropFind should be the problem here.
I'll prepare for a new release were you can use other PropFind types in the WebDavSession.

**Comment by DecaTec** [comment]
I've released version 0.5.2.0.
WebDavSession.ListAsync now uses a so called allprop as default.
When the WebDAV server does not return the expected properties, you can use an overload of ListAsync where a PropFind can be specified (use the static Create... methods in class PropFind to obtain an instance).

That should do the trick, no matter what WebDAV server is used.

For example:
`var propFind = PropFind.CreatePropFindWithEmptyPropertiesAll();
var items = await webDavSession.ListAsync(@"/", propFind);`

The updated NuGet package should be available soon.

**Comment by yookjy** [comment]
Thank you, 
unfortunately occur same error still now.
(The server is fine. Browsing works well in Windows Explorer.)

Error while executing ListAsync (wrong response status code). Expected status code: 207 (MultiStatus); actual status code: 500 (InternalServerError)

**Comment by yookjy** [comment]
If you need to connect to my server, I will tell you the server informations.

**Comment by DecaTec** [comment]
> If you need to connect to my server, I will tell you the server informations.

That'll be really great. Please contact me by mail.
I'll test it with your server then and provide a bugfix if needed.
