### ISSUE TITLE
In combination with OwnCloud based WebDAV, the Uri in the WebDavSessionListItem is wrong?

### ISSUE THREAD

**Issue by StefH** [DecaTec/Portable-WebDAV-Library#13]
I'm using an OwnCloud based WebDAV (stackstorage.com) and when calling the 

```c#
var session = new WebDavSession(...);
string path = "https://***.stackstorage.com/remote.php/webdav/root-folder";
var resources = await session.ListAsync(path);
```
The `Uri` property in the first `WebDavSessionListItem` is defined as 
`
https://***.stackstorage.com/remote.php/webdav/root-folder/remote.php/webdav/root-folder/sub-folder/
`

Instead of

`
https://***.stackstorage.com/remote.php/webdav/root-folder/sub-folder/
`

**Comment by DecaTec** [comment]
Yes, this is a known bug in the current version of the library. It will be fixed in the next version. 
Unfortunately I don't have much time right know. There might also be a problem with IIS WebDAV which I have to investigate before preparing for the next release.
If this is urgent, you can build the project from the latest source, where the bug is fixed already.

**Comment by DecaTec** [comment]
Solved with v0.6.0.0: https://github.com/DecaTec/Portable-WebDAV-Library/releases/tag/v0.6.0.0

**Comment by StefH** [comment]
Can you also update the releasenotes?

**Comment by DecaTec** [comment]
Good point, that's something I forgot.
Done.

**Comment by StefH** [comment]
Still not fixed for me.

Issue is the same, I have to use this hack to get the correct Uri:
```c#
WebDavSessionListItem r = ... ;
Uri fullPath = new Uri(string.Join("/", r.Uri.ToString().Split('/').Distinct()));
```

**Comment by DecaTec** [comment]
Thanks for your feedback, I'll investigate the issue again.

**Comment by DecaTec** [comment]
How do you create the WebDavSession?

The URI's are correct if using:
```c#
var serverUrl = @"http://myserver.de/owncloud/remote.php/webdav/Documents";
var cred = new NetworkCredential("MyUser", "MyPass");
var session = new WebDavSession(serverUrl, cred);
var items = await session.ListAsync(@"/");
```

E.g. URI will be `http://myserver.de/owncloud/remote.php/webdav/Documents/Example.odt`

**Comment by StefH** [comment]
I create the WebDavSession only with credentials. So no serverUrl.

**Comment by DecaTec** [comment]
Strange, same result here:
```c#
var cred = new NetworkCredential("MyUser", "MyPass");
var session = new WebDavSession(cred);
var items = await session.ListAsync(@"http://myserver.de/owncloud/remote.php/webdav/Documents");
```

Will also result in the URI `http://myserver.de/owncloud/remote.php/webdav/Documents/Example.odt`

Are you using the NuGet package or the release-zip? Seems to me as a problem solved with v0.6.0.0.
Could you please check the assembly version of the DLL referenced?

**Comment by StefH** [comment]
I'm using the v0.6.0.0 NuGet.

I'll check the dll version in some hours...
**--> DLL is also 0.6.0.0**

**Comment by StefH** [comment]
OK. I did some more tests and debugging.

It seems that the responseItem.Href (when using stackstorage.com) looks like:
```
uri = "https://***.stackstorage.com/remote.php/webdav/test folder/";
responseItem.Href = "/remote.php/webdav/test%20folder/filename.mp3";
```

So it contains duplicate part (_/remote.php/webdav/test folder/_)

The `CombineUri` method should actually fix this, but it's not working.

See this test:
```c#
[TestMethod]
public void UT_NetFx_UriHelper_CombineUri_withspaces()
{
  Uri baseUri = new Uri("https://xxx.stackstorage.com/remote.php/webdav/folder/folder with spaces and()/");

  Uri relativeUri;
  Uri.TryCreate("/remote.php/webdav/folder/folder%20with%20spaces%20and%28%29/x.mp3", UriKind.RelativeOrAbsolute, out relativeUri);

  Uri combinedUri = UriHelper.CombineUri(baseUri, relativeUri, true);
  Uri expected = new Uri("https://xxx.stackstorage.com/remote.php/webdav/folder/folder with spaces and()/x.mp3");
  Assert.AreEqual(expected, combinedUri);
}
```

**Comment by DecaTec** [comment]
Thanks for pointing this out!
Fixed with https://github.com/DecaTec/Portable-WebDAV-Library/commit/6a2c01f0d2ce70aaacda04f7807b129820f8600e

**Comment by StefH** [comment]
- Can you make a new NuGet for this?
- That Combine method is hard to read, maybe refactor in the future to make it easier and more readable?

**Comment by DecaTec** [comment]
I would wait with the next version v0.6.1.0 until we know if there is a problem with the ETag.
That combine method is quite complex, because it should cope with path repetitions in both Uris.

**Comment by StefH** [comment]
There is still an error, sorry !

```c#
[TestMethod]
public void UT_NetFx_UriHelper_CombineUriWithDuplicatePathEntries()
{
	Uri baseUri = new Uri("https://google.com/remote.php/webdav/folder-sync/x/");
	Uri relativeUri;

	if (!Uri.TryCreate("/remote.php/webdav/folder-sync/x/folder/", UriKind.RelativeOrAbsolute, out relativeUri))
		Assert.Fail();

	Uri combinedUri = UriHelper.CombineUri(baseUri, relativeUri, true);
	Uri expected = new Uri("http://google.de/remote.php/webdav/folder-sync/x/folder/");
	Assert.AreEqual(expected, combinedUri);
}
```

**Comment by DecaTec** [comment]
OK, this was a real bug.

With https://github.com/DecaTec/Portable-WebDAV-Library/commit/f0031fa9ce5620de99a37cb2e0cf714aa841b768 I refactored the CombineUri method and also fixed this bug. Should be fine now - I hope ;)

**Comment by StefH** [comment]
I did not test the following scenario, but I guess this will fail:

```c#
[TestMethod]
public void UT_NetFx_UriHelper_CombineUriWithDuplicatePathEntries2()
{
	Uri baseUri = new Uri("https://google.com/remote.php/webdav/x/x/");
	Uri relativeUri;

	if (!Uri.TryCreate("/remote.php/webdav/x/x/folder/", UriKind.RelativeOrAbsolute, out relativeUri))
		Assert.Fail();

	Uri combinedUri = UriHelper.CombineUri(baseUri, relativeUri, true);
	Uri expected = new Uri("http://google.de/remote.php/webdav/x/x/folder/");
	Assert.AreEqual(expected, combinedUri);
}
````

**Comment by DecaTec** [comment]
OK, you were right. 
Done another rewrite with https://github.com/DecaTec/Portable-WebDAV-Library/commit/2fe1a2879299d2c893e08016fbdfb2ad92018d50
Finally it should work as expected.

**Comment by DecaTec** [comment]
v0.6.1.0 released which should fix all these problems.
Done another refactoring and fixed some other bugs. Also UriHelper should cope with empty strings/null values a lot better now.

NuGet package will be available soon.

Again: Thanks for your help and pushing me into the right direction. :+1:
